/*
 *
 *
 * Distributed under the Apache License.
 * See: https://github.com/frehberg/rtps-gen/blob/master/LICENSE
 */

#ifndef DDS_DCPS_IDL
#define DDS_DCPS_IDL

#include "dds/DdsDcpsDomain.idl"

#endif /* DDS_DCPS_IDL */
