/*
 *
 *
 * Distributed under the Apache License.
 * See: https://github.com/frehberg/rtps-gen/blob/master/LICENSE
 */

#ifndef DDS_DCPS_CONDITIONSEQ_IDL
#define DDS_DCPS_CONDITIONSEQ_IDL

module DDS {
    local interface Condition;
    typedef sequence<Condition> ConditionSeq;
};

#endif  /* DDS_DCPS_CONDITIONSEQ_IDL */
