/*
 *
 *
 * Distributed under the Apache License.
 * See: https://github.com/frehberg/rtps-gen/blob/master/LICENSE
 */

#ifndef DDS_DCPS_DATAREADERSEQ_IDL
#define DDS_DCPS_DATAREADERSEQ_IDL

module DDS {
    local interface DataReader;
    typedef sequence<DataReader> DataReaderSeq;
};

#endif  /* DDS_DCPS_DATAREADERSEQ_IDL */
